# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            JBull
tagline:          'A Java Dev Blog'
description:      'This page is based off the Hyde <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://github.com/sidcitris
baseurl:          /

author:
  name:           'Mike Bullington'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sidcitris
